localization_dict = {'Jump Jets': ['Jump Jets', 'Прыжк. Двиг.'],
                     'M Laser': ['M Laser', 'С Лазер'],
                     'ER M Laser': ['ER M Laser', 'С Лазер УД'],
                     'M P Laser': ['M P Laser', 'С Имп Лазер'],
                     'L Laser': ['L Laser', 'Б Лазер'],
                     'ER L Laser': ['ER L Laser', 'Б Лазер УД'],
                     'L P Laser': ['L P Laser', 'Б Имп Лазер'],
                     'PPC': ['PPC', 'ПИЧ'],
                     'ER PPC': ['ER PPC', 'ПИЧ УД'],
                     'Snub PPC': ['Snub PPC', 'Укор ПИЧ'],
                     'AC/2': ['AC/2', 'АП/2'],
                     'AC/5': ['AC/5', 'АП/5'],
                     'AC/10': ['AC/10', 'АП/10'],
                     'AC/20': ['AC/20', 'АП/20'],
                     'UAC/2': ['UAC/2', 'УАП/2'],
                     'UAC/5': ['UAC/5', 'УАП/5'],
                     'UAC/10': ['UAC/10', 'УАП/10'],
                     'UAC/20': ['UAC/20', 'УАП/20'],
                     'LBX/2': ['LBX/2', 'ЛБХ/2'],
                     'LBX/5': ['LBX/5', 'ЛБХ/5'],
                     'LBX/10': ['LBX/10', 'ЛБХ/10'],
                     'LBX/20': ['LBX/20', 'ЛБХ/20'],
                     'Gauss Rifle': ['Gauss Rifle', 'Гаусс Пушка'],
                     'SRM2': ['SRM2', 'РМД2'],
                     'SRM4': ['SRM4', 'РМД4'],
                     'SRM6': ['SRM6', 'РМД6'],
                     'LRM5': ['LRM5', 'РБД5'],
                     'LRM10': ['LRM10', 'РБД10'],
                     'LRM15': ['LRM15', 'РБД15'],
                     'LRM20': ['LRM20', 'РБД20'],
                     'MG': ['MG', 'Пулемет'],
                     'S Laser': ['S Laser', 'М Лазер'],
                     'ER S Laser': ['ER S Lasers', 'М Лазер УД'],
                     'S P Laser': ['S P Laser', 'М Имп Лазер'],
                     'Free Weight': ['Free Weight, Tonn: ', 'Свободный вес, Тонн: '],
                     'Light': ['Light', 'Легк'],
                     'Heavy': ['Heavy', 'Тяж'],
                     'Sturm': ['Sturm', 'Штурм'],
                     'None': ['None', 'Нет'],
                     'Energy': ['Energy', 'Энергетическое'],
                     'Ballistic': ['Ballistic', 'Баллистическое'],
                     'Missile': ['Missile', 'Ракетное'],
                     'Support': ['Support', 'Поддержка'],
                     'Calculation': ['Calculation', 'Расчет'],
                     'Oops': ['Failed to build the assembly. Change the calculation parameters.',
                              'Не удалось подобрать сборку. Измените параметры расчета.'],
                     'Best weapons: ': ['Best weapons: ', 'Лучшее оружие: '],
                     'Summary weight: ': ['Summary weight: ', 'Суммарный вес: '],
                     'Max Damage: ': ['Max Damage: ', 'Максимальный урон: '],
                     'Heatsink weight: ': ['Heatsink weight: ', 'Вес радиаторов: '],
                     'Ammunition weight: ': ['Ammunition weight: ', 'Вес боекомплекта: '],
                     'Unallocated weight: ': ['Unallocated weight: ', 'Нераспределенный вес: '],
                     'Delta heat: ': ['Delta heat: ', 'Дельта температуры: '],
                     'Start': ['Specify the free weight, select the weapon, its quantity and modification. '
                               'Then click the "Calculation" button.',
                               'Укажите свободный вес, выберите оружие, его количество и модификацию. '
                               'Затем нажмите кнопку "Расчет".'],
                     'GUIDE': ['   GUIDE', ' Инструкция']

                     }